title: Andreas Jangefalk
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
# 
# url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact

social:
   github: jangefalk
   twitter: jangefalk
#    facebook: brianmaierjr
   email: andreas.jangefalk@gmail.com

google_analytics: "UA-58263416-1"
